#!/bin/bash

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

ln -sf "$SCRIPT_DIR"/micro/settings.json "$XDG_CONFIG_HOME"/micro/settings.json
ln -sf "$SCRIPT_DIR"/fish/fish_prompt.fish "$XDG_CONFIG_HOME"/fish/functions/fish_prompt.fish
ln -sf "$SCRIPT_DIR"/sxhkd/sxhkdrc "$XDG_CONFIG_HOME"/sxhkd/sxhkdrc
